[[plugins]]                                                                 
repo   = 'Shougo/unite.vim'

# ファイルタイプ=python の際に読み込む
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'vim-syntastic/syntastic'
on_ft = ['python']
hook_post_source = 'let g:syntastic_python_checkers = ["flake8"]'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['swift']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_ft = ['swift']
hook_post_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = ['swift']
hook_post_source = 'let g:deoplete#sources#swift#daemon_autostart = 1'

[[plugins]]
repo = 'kballard/vim-swift'
on_ft = ['swift']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

